public with sharing class RFA_Utility_Configure {
	
	/*
		COA
	*/	
	public static final Map<String, String> Gr1FunctionToAcronym = new Map<String, String>{
		'Commercial' => 'CCO', 
		'Supply Chain' => 'CSCO',
		'Finance' => 'CFO', 
		'HR' => 'CHRO', 
		'Procurement' => 'CPO', 
		'IT' => 'CITO', 
		'BI' => 'CBIO', 
		'Business Integration' => 'CBIO', 
		'PAC' => 'CPACO', 
		'Legal' => 'CLO' //,
		//'CokeOne' => 'CFO' //temporary
	}; //CEO	
		
	/*
		Milestone + RFA
	*/
	public static final String RM_Initiate_Approved = 'Initiate Approved'; //'Initiate承認済み';
	public static final String RM_Charter_Approved = 'Charter Approved'; //'Chater承認済み';	
	public static final String RM_Close_Approved = 'Close-Out Approved'; //'CloseOut承認済み';	
	
	/*
		Seal Paperless
	*/
	//public static Id idSealAdmin = '005N0000000tPNB';
	//public static Id idKawamotoNaruhiko = '00510000001rhvJ';
	//public static Id idNakanoToshio = '00510000001rhvi';
	
	
	
	

}