<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <fieldUpdates>
        <fullName>HiddenButton</fullName>
        <description>カスタムボタンの非表示</description>
        <field>RecordTypeId</field>
        <lookupValue>NoButton</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>カスタムボタンの非表示</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ShowButton</fullName>
        <description>カスタムボタンを表示</description>
        <field>RecordTypeId</field>
        <lookupValue>HasButton</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>カスタムボタンの表示</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <rules>
        <fullName>HiddenButton</fullName>
        <actions>
            <name>HiddenButton</name>
            <type>FieldUpdate</type>
        </actions>
        <active>false</active>
        <criteriaItems>
            <field>CreateReportHistory__c.DeliveryID__c</field>
            <operation>equals</operation>
        </criteriaItems>
        <description>カスタムボタンを非表示</description>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>ShowButton</fullName>
        <actions>
            <name>ShowButton</name>
            <type>FieldUpdate</type>
        </actions>
        <active>false</active>
        <criteriaItems>
            <field>CreateReportHistory__c.DeliveryID__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <description>カスタムボタンを表示するかしないか切り替え</description>
        <triggerType>onAllChanges</triggerType>
    </rules>
</Workflow>
