@isTest(SeeAllData=false) 
public with sharing class RFATestDataTempLogic {

	static testmethod void RFA_Test_Tempa1(){
		RFATestDataTemp13.Method1();
		RFATestDataTemp13.Method2();
		RFATestDataTemp13.Method3();
		RFATestDataTemp13.Method4();
		RFATestDataTemp13.Method5();
		RFATestDataTemp13.Method6();
		RFATestDataTemp13.Method7();
		RFATestDataTemp13.Method8();
		RFATestDataTemp13.Method9();
		RFATestDataTemp13.Method10();
		RFATestDataTemp13.Method11();
	}
	static testmethod void RFA_Test_Tempa2(){
		RFATestDataTemp13.Method12();
		RFATestDataTemp13.Method13();
		RFATestDataTemp13.Method14();
	}	
	
	static testmethod void RFA_Test_Tempa3(){
		RFATestDataTemp13.Method21();
		RFATestDataTemp13.Method22();
		RFATestDataTemp13.Method23();
		RFATestDataTemp13.Method24();
		RFATestDataTemp13.Method25();
		RFATestDataTemp13.Method26();
		RFATestDataTemp13.Method27();
		RFATestDataTemp13.Method28();
		RFATestDataTemp13.Method29();
		RFATestDataTemp13.Method30();
		RFATestDataTemp13.Method31();
	}	
	
	static testmethod void RFA_Test_Tempa4(){
		RFATestDataTemp13.Method32();
		RFATestDataTemp13.Method33();
		RFATestDataTemp13.Method34();
	}	
	


	static testmethod void RFA_Test_Tempa11(){
		RFATestDataTemp14.Method1();
		RFATestDataTemp14.Method2();
		RFATestDataTemp14.Method3();
		RFATestDataTemp14.Method4();
		RFATestDataTemp14.Method5();
		RFATestDataTemp14.Method6();
		RFATestDataTemp14.Method7();
		RFATestDataTemp14.Method8();
		RFATestDataTemp14.Method9();
		RFATestDataTemp14.Method10();
		RFATestDataTemp14.Method11();
	}
	static testmethod void RFA_Test_Tempa22(){
		RFATestDataTemp14.Method12();
		RFATestDataTemp14.Method13();
		RFATestDataTemp14.Method14();
	}	
	
	static testmethod void RFA_Test_Tempa33(){
		RFATestDataTemp14.Method21();
		RFATestDataTemp14.Method22();
		RFATestDataTemp14.Method23();
		RFATestDataTemp14.Method24();
		RFATestDataTemp14.Method25();
		RFATestDataTemp14.Method26();
		RFATestDataTemp14.Method27();
		RFATestDataTemp14.Method28();
		RFATestDataTemp14.Method29();
		RFATestDataTemp14.Method30();
		RFATestDataTemp14.Method31();
	}	
	
	static testmethod void RFA_Test_Tempa44(){
		RFATestDataTemp14.Method32();
		RFATestDataTemp14.Method33();
		RFATestDataTemp14.Method34();
	}	




	static testmethod void RFA_Test_Tempa111(){
		RFATestDataTemp15.Method1();
		RFATestDataTemp15.Method2();
		RFATestDataTemp15.Method3();
		RFATestDataTemp15.Method4();
		RFATestDataTemp15.Method5();
		RFATestDataTemp15.Method6();
		RFATestDataTemp15.Method7();
		RFATestDataTemp15.Method8();
		RFATestDataTemp15.Method9();
		RFATestDataTemp15.Method10();
		RFATestDataTemp15.Method11();
	}
	static testmethod void RFA_Test_Tempa222(){
		RFATestDataTemp15.Method12();
		RFATestDataTemp15.Method13();
		RFATestDataTemp15.Method14();
	}	
	
	static testmethod void RFA_Test_Tempa333(){
		RFATestDataTemp15.Method21();
		RFATestDataTemp15.Method22();
		RFATestDataTemp15.Method23();
		RFATestDataTemp15.Method24();
		RFATestDataTemp15.Method25();
		RFATestDataTemp15.Method26();
		RFATestDataTemp15.Method27();
		RFATestDataTemp15.Method28();
		RFATestDataTemp15.Method29();
		RFATestDataTemp15.Method30();
		RFATestDataTemp15.Method31();
	}	
	
	static testmethod void RFA_Test_Tempa444(){
		RFATestDataTemp15.Method32();
		RFATestDataTemp15.Method33();
		RFATestDataTemp15.Method34();
	}	

	static testmethod void RFA_Test_Tempa1_6(){
		RFATestDataTemp16.Method1();
		RFATestDataTemp16.Method2();
		RFATestDataTemp16.Method3();
		RFATestDataTemp16.Method4();
		RFATestDataTemp16.Method5();
		RFATestDataTemp16.Method6();
		RFATestDataTemp16.Method7();
		RFATestDataTemp16.Method8();
		RFATestDataTemp16.Method9();
		RFATestDataTemp16.Method10();
		RFATestDataTemp16.Method11();
	}
	static testmethod void RFA_Test_Tempa2_6(){
		RFATestDataTemp16.Method12();
		RFATestDataTemp16.Method13();
		RFATestDataTemp16.Method14();
	}	
	static testmethod void RFA_Test_Tempa3_6(){
		RFATestDataTemp16.Method21();
		RFATestDataTemp16.Method22();
		RFATestDataTemp16.Method23();
		RFATestDataTemp16.Method24();
		RFATestDataTemp16.Method25();
		RFATestDataTemp16.Method26();
		RFATestDataTemp16.Method27();
		RFATestDataTemp16.Method28();
		RFATestDataTemp16.Method29();
		RFATestDataTemp16.Method30();
		RFATestDataTemp16.Method31();
	}	
	static testmethod void RFA_Test_Tempa4_6(){
		RFATestDataTemp16.Method32();
		RFATestDataTemp16.Method33();
		RFATestDataTemp16.Method34();
	}	
	
	
	static testmethod void RFA_Test_Tempa1_7(){
		RFATestDataTemp17.Method1();
		RFATestDataTemp17.Method2();
		RFATestDataTemp17.Method3();
		RFATestDataTemp17.Method4();
		RFATestDataTemp17.Method5();
		RFATestDataTemp17.Method6();
		RFATestDataTemp17.Method7();
		RFATestDataTemp17.Method8();
		RFATestDataTemp17.Method9();
		RFATestDataTemp17.Method10();
		RFATestDataTemp17.Method11();
	}
	static testmethod void RFA_Test_Tempa2_7(){
		RFATestDataTemp17.Method12();
		RFATestDataTemp17.Method13();
		RFATestDataTemp17.Method14();
	}	
	static testmethod void RFA_Test_Tempa3_7(){
		RFATestDataTemp17.Method21();
		RFATestDataTemp17.Method22();
		RFATestDataTemp17.Method23();
		RFATestDataTemp17.Method24();
		RFATestDataTemp17.Method25();
		RFATestDataTemp17.Method26();
		RFATestDataTemp17.Method27();
		RFATestDataTemp17.Method28();
		RFATestDataTemp17.Method29();
		RFATestDataTemp17.Method30();
		RFATestDataTemp17.Method31();
	}	
	static testmethod void RFA_Test_Tempa4_7(){
		RFATestDataTemp17.Method32();
		RFATestDataTemp17.Method33();
		RFATestDataTemp17.Method34();
	}		
	


	static testmethod void RFA_Test_Tempa1_8(){
		RFATestDataTemp18.Method1();
		RFATestDataTemp18.Method2();
		RFATestDataTemp18.Method3();
		RFATestDataTemp18.Method4();
		RFATestDataTemp18.Method5();
		RFATestDataTemp18.Method6();
		RFATestDataTemp18.Method7();
		RFATestDataTemp18.Method8();
		RFATestDataTemp18.Method9();
		RFATestDataTemp18.Method10();
		RFATestDataTemp18.Method11();
	}
	static testmethod void RFA_Test_Tempa2_8(){
		RFATestDataTemp18.Method12();
		RFATestDataTemp18.Method13();
		RFATestDataTemp18.Method14();
	}	
	static testmethod void RFA_Test_Tempa3_8(){
		RFATestDataTemp18.Method21();
		RFATestDataTemp18.Method22();
		RFATestDataTemp18.Method23();
		RFATestDataTemp18.Method24();
		RFATestDataTemp18.Method25();
		RFATestDataTemp18.Method26();
		RFATestDataTemp18.Method27();
		RFATestDataTemp18.Method28();
		RFATestDataTemp18.Method29();
		RFATestDataTemp18.Method30();
		RFATestDataTemp18.Method31();
	}	
	static testmethod void RFA_Test_Tempa4_8(){
		RFATestDataTemp18.Method32();
		RFATestDataTemp18.Method33();
		RFATestDataTemp18.Method34();
	}		
	
	
		
}